DECLARE
	V_MSQL VARCHAR2(4000 CHAR);
	V_COUNT NUMBER(16);
BEGIN
	V_MSQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE <> ''R'' AND STATUS = ''DISABLED''';
    EXECUTE IMMEDIATE V_MSQL INTO V_COUNT;
    
    IF V_COUNT > 0 THEN
        FOR I IN (SELECT TABLE_NAME, CONSTRAINT_NAME --disable first the foreign key
            FROM USER_CONSTRAINTS
            WHERE CONSTRAINT_TYPE <> 'R' AND STATUS = 'DISABLED')
        LOOP
            V_MSQL := 'ALTER TABLE ' ||I.TABLE_NAME|| ' ENABLE CONSTRAINT ' ||I.CONSTRAINT_NAME;
            EXECUTE IMMEDIATE V_MSQL;
        END LOOP I;
    END IF;
    
    V_MSQL := 'SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE STATUS = ''DISABLED''';
    EXECUTE IMMEDIATE V_MSQL INTO V_COUNT;
    
    IF V_COUNT > 0 THEN
        FOR I IN (SELECT TABLE_NAME, CONSTRAINT_NAME -- then disable all constraints
            FROM USER_CONSTRAINTS
            WHERE STATUS = 'DISABLED')
        LOOP
            V_MSQL := 'ALTER TABLE ' ||I.TABLE_NAME|| ' ENABLE CONSTRAINT ' ||I.CONSTRAINT_NAME;
            EXECUTE IMMEDIATE V_MSQL;
        END LOOP I;
    END IF;
END;
/
EXIT