DECLARE

    TYPE T_TABLAS IS TABLE OF VARCHAR2(150);      
    TYPE T_ARRAY_TABLAS IS TABLE OF T_TABLAS;          
    V_TEMP_TABLAS  T_TABLAS;
    C_TABLA T_ARRAY_TABLAS := T_ARRAY_TABLAS(T_TABLAS('REM01','GPV_GASTOS_PROVEEDOR'));
    V_ESQUEMA VARCHAR2(30 CHAR) := 'REM01';

BEGIN

 DBMS_OUTPUT.PUT_LINE('********************' );
 DBMS_OUTPUT.PUT_LINE('**ACTIVAMOS RESTRICCIONES CLAVE AJENA**' );
 DBMS_OUTPUT.PUT_LINE('********************' );
 
 FOR I IN C_TABLA.FIRST .. C_TABLA.LAST
 LOOP
      V_TEMP_TABLAS := C_TABLA(I);
     
      FOR J IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM SYS.USER_CONSTRAINTS WHERE CONSTRAINT_TYPE='R'
                AND STATUS='DISABLED' AND TABLE_NAME = V_TEMP_TABLAS(2))
      LOOP
          BEGIN                
                     EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.' || J.TABLE_NAME || ' ENABLE CONSTRAINT ' || J.CONSTRAINT_NAME;
                     
       EXCEPTION WHEN OTHERS THEN
             NULL;
       END;
      END LOOP;            
 END LOOP; 

 DBMS_OUTPUT.PUT_LINE('*******************************' );
 DBMS_OUTPUT.PUT_LINE('**FALTA ACTIVAR RESTRICCIONES**' );
 DBMS_OUTPUT.PUT_LINE('*******************************' );

  FOR J IN (SELECT TABLE_NAME, CONSTRAINT_NAME
              FROM SYS.USER_CONSTRAINTS
             WHERE  STATUS='DISABLED')
   LOOP
  BEGIN                
EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.' || J.TABLE_NAME || ' ENABLE CONSTRAINT ' || J.CONSTRAINT_NAME;
 
  EXCEPTION WHEN OTHERS THEN
  NULL;
  END;
  END LOOP;  

  FOR J IN (SELECT TABLE_NAME, CONSTRAINT_NAME
              FROM SYS.USER_CONSTRAINTS
             WHERE  STATUS='DISABLED')
   LOOP
  BEGIN                
EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.' || J.TABLE_NAME || ' ENABLE CONSTRAINT ' || J.CONSTRAINT_NAME;  
  EXCEPTION WHEN OTHERS THEN
  NULL;
  END;
  END LOOP;
END;