DECLARE

TYPE T_TABLAS IS TABLE OF VARCHAR2(150);      
TYPE T_ARRAY_TABLAS IS TABLE OF T_TABLAS;          
V_TEMP_TABLAS  T_TABLAS;

C_TABLA T_ARRAY_TABLAS := T_ARRAY_TABLAS(
   T_TABLAS('REM01','GPV_GASTOS_PROVEEDOR')
                                       );
                                       
V_ESQUEMA VARCHAR2(30 CHAR) := 'REM01';

BEGIN



 DBMS_OUTPUT.PUT_LINE('********************' );
 DBMS_OUTPUT.PUT_LINE('**DESACTIVAMOS RESTRICCIONES CLAVE AJENA**' );
 DBMS_OUTPUT.PUT_LINE('********************' );

 FOR I IN C_TABLA.FIRST .. C_TABLA.LAST
 LOOP
    BEGIN
      V_TEMP_TABLAS := C_TABLA(I);
     
      FOR J IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM SYS.USER_CONSTRAINTS WHERE CONSTRAINT_TYPE='R' AND STATUS='ENABLED' AND TABLE_NAME = V_TEMP_TABLAS(2))
      LOOP
          BEGIN
                 EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.' || J.TABLE_NAME || ' DISABLE CONSTRAINT ' || J.CONSTRAINT_NAME;        
          END;    
      END LOOP;    
     
   EXCEPTION WHEN OTHERS THEN
     NULL;
   END;
 END LOOP;
 DBMS_OUTPUT.PUT_LINE('********************' );
 DBMS_OUTPUT.PUT_LINE('**DESACTIVAMOS RESTRICCIONES CLAVE PRIMARIA**' );
 DBMS_OUTPUT.PUT_LINE('********************' );

 FOR I IN C_TABLA.FIRST .. C_TABLA.LAST
 LOOP
    BEGIN
      V_TEMP_TABLAS := C_TABLA(I);
     
      FOR J IN (SELECT TABLE_NAME, CONSTRAINT_NAME FROM SYS.USER_CONSTRAINTS WHERE CONSTRAINT_TYPE='P' AND STATUS='ENABLED' AND TABLE_NAME = V_TEMP_TABLAS(2))
      LOOP
          BEGIN
               
                 EXECUTE IMMEDIATE 'ALTER TABLE '||V_ESQUEMA||'.' || J.TABLE_NAME || ' DISABLE CONSTRAINT ' || J.CONSTRAINT_NAME || ' CASCADE ';        
          END;    
      END LOOP;    
     
   EXCEPTION WHEN OTHERS THEN
     NULL;
   END;
 END LOOP;

END;