CREATE OR REPLACE FUNCTION DAME_PASSWORD RETURN VARCHAR2 AS 
  VV_RANVALUE VARCHAR(11);
BEGIN
  VV_RANVALUE := SUBSTR(CAST(dbms_random.value(1,10) AS VARCHAR),1,10);
  VV_RANVALUE := SUBSTR(DBMS_OBFUSCATION_TOOLKIT.md5 (input => UTL_RAW.cast_to_raw(VV_RANVALUE)),1,10);
  RETURN VV_RANVALUE;
END DAME_PASSWORD;